#include: package:pedantic/analysis_options.1.11.0.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false