name: veggie_android_seasons
description: A new Flutter project.

version: 3.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "android/app/src/main/res/drawable/launcher_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: 'android/app/src/main/res/drawable/launcher_icon.png'
  android: true
  ios: false
  web: false
  android12: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
          weight: 400
